### PR TITLE
Patch 3 (botpack)

### PR DESCRIPTION
**Pull request by Reorn**

### CODE REVIEW

**Comment by NeonKnightOA** [comment]
Then there's a bug that needs to be fixed in v469. Abbrev is supposed to take precedence over String.

**Comment by Reorn** [comment]
Abbrev HAS precedence over String.
The problem is different:

line Parameter="" ignored by Engine. Need Parameter="Value"
As  exsample:
if in localization file 
; EN: OrderAbbrev[0]="Defend"
OrderAbbrev[0]=""

in game will be: "Defend"
line OrderAbbrev[0]="" ignored by Engine.

**Comment by NeonKnightOA** [comment]
The ideal situation should be like this:

Abbrev.??t
String.??t
Abbrev.int
String.int

This needs to be made into an issue in UnrealTournamentPatches.

**Comment by NeonKnightOA** [comment]
I've merged your commit anyways.

**Pull request merged**
