### PR TITLE
greek update

### PR DESCRIPTION
**Pull request by LDinos**
About 80% done with UT99 translation

### CODE REVIEW

**Comment by LDinos** [comment]
UT99 almost completely done in greek, just need to do Core and UnrealShare

**Comment by LDinos** [comment]
Finished greek translation for ut99

**Comment by LDinos** [comment]
Slight fixes to inventory names and strings that were too long

**Comment by NeonKnightOA** [comment]
Excellent! Is it ready to go, then?

Sorry for the delay, I've been dealing with some personal issues!

**Comment by LDinos** [comment]
> Excellent! Is it ready to go, then? @LDinos
> 
> Sorry for the delay, I've been dealing with some personal issues!

Should be good! If I find anything out of shape, I will work on fixing it in the new year :)

**Comment by NeonKnightOA** [comment]
Cool! We get a new language then. Once I finish setting up some things, I'll see what can I do about your work. Thank you so much!

BTW, how does it look in-game?

**Comment by LDinos** [comment]
> 

https://imgur.com/a/PpMtIrV

Everything looks okay, one problem only is the scoreboard (take a look at the scoreboard pic in the imgur gallery). I think the "FREELANCING", "SUPPORTING", etc font doesn't accept greek characters so they show up as empty

**Comment by NeonKnightOA** [comment]
You might want to report that to https://github.com/UnrealTournamentPatches/issues. Sounds like a rendering mistake.

**Comment by NeonKnightOA** [comment]
Also check the Unreal Greek folder. Several of your files still have the .template extension rather than .elt.

**Comment by LDinos** [comment]
Oh, the Unreal folder is all WIP stuff that I didn't work on too much, my bad for letting them be so unorganized in there 😅
If you want me I can delete the elt folder from the WIP folder (from Unreal) entirely and re-commit, I didn't do any work in there anyways.

**Comment by NeonKnightOA** [comment]
You can put the WIP files in `WIP/WIP-Templates/elt` and the finished files in `WIP/WIP-FinishedFiles/elt`. And once you have an entire language running, move directly to `SystemLocalized/elt`

**Comment by LDinos** [comment]
Should be okay now, I didn't have any WIP stuff in Unreal, I was doing everything in real time in the WIP finished folder, so now I fixed that organizing, I think everything should be okay now and ready. Let me know if you see anything else that might be weird

**Comment by NeonKnightOA** [comment]
Excellent! Merging!

**Comment by NeonKnightOA** [comment]
Thank you for your efforts!

**Comment by NeonKnightOA** [comment]
Will you do Unreal next? You already have the templates, some of the files can even be mirrored.

**Comment by LDinos** [comment]
Perhaps! The initial idea was to do Unreal first, ut99 later. I stopped after seeing all the translator events :P They were too much for me so I worked on ut99 instead. I also recently found a job so I am not sure if time allows it for that. I love translating games so I will definitely do it someday, just not too sure when...

**Comment by NeonKnightOA** [comment]
Oh, in that case you should've started with the smaller files first and leave the "heavier" ones for the end.

**Pull request merged**
