### PR TITLE
Revise german translation of UT

### PR DESCRIPTION
**Pull request by hosterholz**

### CODE REVIEW

**Comment by NeonKnightOA** [comment]
Tagging @JanUrbansky .

**Comment by JanUrbansky** [comment]
My personally opinion on this...don't change the salutations...it sounds so impersonal. It's still a game not a business letter. What the others think?

**Comment by hosterholz** [comment]
Sometimes the translation switched between formal and informal. For example in AS-Mazon.det:

> *Dein* Feind benutzt Tarydium, ein mächtiges und flüchtiges Element, um seine Kriegsmaschinen anzutreiben. *Sie müssen* die Basis infiltrieren, indem *Sie* zuerst die beiden Gegengewichte außerhalb des Westflügels der Festung zerstören.

I tried to keep the style consistent. The translation uses the formal form in most places. I agree that it does not sound right especially in the menus. It could be changed from formal form to the informal.

**Comment by JanUrbansky** [comment]
> Sometimes the translation switched between formal and informal. For example in AS-Mazon.det:
> 
> > _Dein_ Feind benutzt Tarydium, ein mächtiges und flüchtiges Element, um seine Kriegsmaschinen anzutreiben. _Sie müssen_ die Basis infiltrieren, indem _Sie_ zuerst die beiden Gegengewichte außerhalb des Westflügels der Festung zerstören.
> 
> I tried to keep the style consistent. The translation uses the formal form in most places. I agree that it does not sound right especially in the menus. It could be changed from formal form to the informal.

Yeah you're right in that point...the original translation was wrong. What I mean why do you use formal "Sie" instead of the informal "Du" condition? The game was originally written in informal salutation. I don't think to change this aspect.

**Comment by JanUrbansky** [comment]
> The "original" was a computer-generated localization with Unreal stuff and a few fixes. Original UT didn't ship with German localization because of what we already know.

Sorry yes thats right...original was only released in four languages...not in german ;)

**Review by JanUrbansky — COMMENTED** [review]
its ok

**Comment by NeonKnightOA** [comment]
Are we good to go then? @hosterholz ?

**Comment by hosterholz** [comment]
Still working on Botpack.det. I will remove the WIP flag when I'm done.

**Comment by NeonKnightOA** [comment]
Take your time with that one, them. It's by far the longest file in all the games.

**Comment by NeonKnightOA** [comment]
Excellent! I've been told this isn't going to make the cut for RC2, but for RC3 it'll do.

**Pull request merged**
